### ISSUE TITLE
Kanal is slower than crossbeam

### ISSUE THREAD

**Issue by capgelka** [fereidani/kanal#32]
I was experimenting with multithreaded algorithms in Rust and to improve perfomance tried for one which is based on communication through the channel to replace `crossbeam ` channels with `kanal`.

Here is the code 
```rust
pub fn multithread_map_kanal_channel<T, R, F>(
    input: Vec<T>,
    f: F
) -> anyhow::Result<Vec<R>>
    where
        T: Send + Sync + Clone,
        R: Send + Sync + Default + Clone,
        F: Fn(T) -> R + Send + Sync + Copy,
{
    let size = input.len();

    if size == 0 {
        return Ok(vec![]);
    }

    let num_threads = num_cpus::get() - 1; // one thread to collect results

    let mut results = vec![Default::default(); size];
    let chunk_size = size / num_threads;
    let (snd, rcv) = kanal::bounded(size);
    let res = crossbeam::thread::scope(|s| {
        for (i, chunk) in input.chunks(chunk_size).enumerate() {
            let snd_cloned = snd.clone();
            s.spawn(move |_| {
                for (j, item) in chunk.iter().enumerate() {
                    snd_cloned
                        .send((i * chunk_size + j, f(item.clone())))
                        .unwrap();
                }
            });
        }
        s.spawn(|_| {
            let mut counter = size;
            while counter > 0 {
                let (index, value) = rcv.recv().unwrap();
                results[index] = value;
                counter -= 1;
            }
        });
    });
    res.map(|_| results)
        .map_err(|_| anyhow::anyhow!("One of the threads failed"))
}
```

crossbeam implementation is the same, only another channel is used.

I used the following code for benchmark.

```rust
fn gen_data(n: usize) -> Vec<u32> {
    let mut rng = rand::thread_rng();
    (0..n).map(|_| rng.gen_range(0..1000)).collect()
}

fn dup(x: u32) -> u32 {
    x * 2
}

fn fib(n: u32) -> u32 {
    let mut a = 0;
    let mut b = 1;

    match n {
        0 => b,
        _ => {
            for _ in 0..n {
                let c = a + b;
                a = b;
                b = c;
            }
            b
        }
    }
}

// Define the benchmark function
fn bench_parallel_map(c: &mut Criterion) {

    // Benchmark the parallel_map function with different input sizes
    let mut group = c.benchmark_group("parallel_map");
    for n in [150, 1000, 5_000, 20_000].iter() {
        group.bench_with_input(format!("crossbeam_chan_dup_{}", n), n, |b, &n| {
            b.iter(|| multithread_map_crossbeam_channel(gen_data(n), dup))
        });
        group.bench_with_input(format!("kanal_chan_dup_{}", n), n, |b, &n| {
            b.iter(|| multithread_map_kanal_channel(gen_data(n), dup))
        });

        group.bench_with_input(format!("crossbeam_chan_fib_{}", n), n, |b, &n| {
            b.iter(|| multithread_map_crossbeam_channel(gen_data(n), fib))
        });
        group.bench_with_input(format!("kanal_chan_fib_{}", n), n, |b, &n| {
            b.iter(|| multithread_map_kanal_channel(gen_data(n), fib))
        });
    }
    group.finish();
}


criterion_group!(benches, bench_parallel_map);
criterion_main!(benches);
```

The benchmark output for Apple `M1` is in the attachment, I also did the similar experiment on an old i5 with 4 cores on Linux, and `crossbeam` also beats `kanal`.

[bench.txt](https://github.com/fereidani/kanal/files/11115604/bench.txt)

**Comment by fereidani** [comment]
Hello,

Thank you for taking the time to evaluate our library and for contributing your own benchmark. I appreciate your input and feedback. However, I would like to clarify a few points regarding the performance comparisons between Crossbeam channels and Kanal.

While it is true that Crossbeam channels may outperform Kanal in certain tests, our findings indicate that Kanal generally surpasses Crossbeam by a significant margin, particularly when the channel buffer size is less than the required amount (e.g., 0 or 1), which is a common scenario in real-world applications.

We maintain a comprehensive test suite for our library which is a highly modified fork of a crossbeam channel benchmark and would be more than happy to incorporate any relevant code contributions to further improve its accuracy and relevance. However, I am unable to review and assess each individual benchmark submission due to resource constraints. (https://github.com/fereidani/rust-channel-benchmarks)

Regarding your benchmark, I noticed that it randomizes the input values for the Fibonacci algorithm, which results in different inputs for each test run. This approach might introduce a fairness concern, as the computational cost of the Fibonacci algorithm can vary significantly depending on the input value.

Once again, thank you for your interest in this library, and I look forward to any further feedback and contributions you may have.

Best regards
